Models/Course.cs
namespace dotnet_basics.Models;

public class Course
{
    public int Id { get; set; }
    public string  Title { get; set; }  
    public string  Image { get; set; }  

    public bool  IsActive { get; set; }
    public bool IsHome { get; set; }
}

Models/ErrorViewModel.cs
namespace dotnet_basics.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Product.cs
namespace dotnet_basics.Models;

    public class Product
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public string productDetail { get; set; }
        public double productPrice { get; set; }
        public string productImage { get; set; }
        public bool  productIsStock { get; set; }

        public int StockPieces {get; set;}

        public bool IsHome { get; set; }
        
    }

Controllers/CourseController.cs
using dotnet_basics.Models;
using Microsoft.AspNetCore.Mvc;

namespace dotnet_basics.Controllers;



    public class CourseController : Controller
    {
        
        //listeyi tekrar tekrar yazmank yerıne Listeyi en üstten tanımladık böylece hepsinin erişimi sağlanmıs oldu
        List<Course> kurslar = new List<Course>{
                new Course
                {
                    Id = 1,
                    Title = "Javascript kursu",
                    Image = "tel-1.jpg",
                    IsActive = true,
                    IsHome = true
                },
                new Course
                {
                    
                    Id = 2,
                    Title = "React kursu",
                    Image = "tel-2.jpg",
                    IsActive = true,
                    IsHome = false                },
                new Course
                {
                    Id = 3,
                    Title = "Javascript kursu",
                    Image = "tel-1.jpg",
                    IsActive = true,
                    IsHome = false
                },
                new Course
                {
                    Id = 4,
                    Title = "React kursu",
                    Image = "tel-2.jpg",
                    IsActive = true,
                    IsHome = true                },
                new Course
                {
                    Id = 5,
                    Title = "Javascript kursu",
                    Image = "tel-1.jpg",
                    IsActive = true,
                    IsHome = true
                },
                new Course
                {
                    Id = 6,
                    Title = "React kursu",
                    Image = "tel-2.jpg",
                    IsActive = true,
                    IsHome = true                },
                new Course
                {
                    Id = 7,
                    Title = "Javascript kursu",
                    Image = "tel-1.jpg",
                    IsActive = true,
                    IsHome = true
                },
                new Course
                {
                    Id = 8,
                    Title = "React kursu",
                    Image = "tel-2.jpg",
                    IsActive = true,
                    IsHome = false                },
                new Course
                {
                    Id = 9,
                    Title = "Javascript kursu",
                    Image = "tel-1.jpg",
                    IsActive = true,
                    IsHome = true
                },
                new Course
                {
                    Id = 10,
                    Title = "React kursu",
                    Image = "tel-2.jpg",
                    IsActive = true,
                    IsHome = false               
                     },
                new Course
                {
                    Id = 11,
                    Title = "Javascript kursu",
                    Image = "tel-1.jpg",
                    IsActive = true,
                    IsHome = true
                },
                new Course
                {
                    Id = 12,
                    Title = "React kursu",
                    Image = "tel-2.jpg",
                    IsActive = true,
                    IsHome = false            
                }
            };

        public ActionResult  Index()  
        {
            

            return View(kurslar);
        }

        
        //localhost:5052/course/list

        public ActionResult  List()
        {
            
          




            return View(kurslar);
        }
        

        //localhost:5052/course/details
        public ActionResult  Details(int id) //id o anda ulaşmak istediğimiz kursun id'si
        {
            
            Course? kurs = kurslar.Where(a => a.Id == id).FirstOrDefault();//bu method bu id ile eşleşen ilk kursu bulur ve onu döndürür. Eğer böyle bir kurs yoksa null döner.ToList() ise bütün listeyi döndürür.


            return View(kurs);
        }
    }

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace dotnet_basics.Controllers;

public class HomeController:Controller 
{
    
    public ActionResult Index()
    {
        int sayi1 = 10;
        int sayi2 = 20;

        int toplam = sayi1 + sayi2;

        ViewData["Toplam"] = toplam; //Toplam key toplam value değeridir Diğer index kısmında bu değeri göstermek için Toplam keyini kullanırız kullanıyoruz.
        return View();   
    }
    

    public ActionResult About()  
    {
        return View();
    }


    public ActionResult Contact()   
    {
        return View();
    }
}

Controllers/ProductsController.cs
using dotnet_basics.Models;
using Microsoft.AspNetCore.Mvc;

namespace dotnet_basics.Controllers;

    public class ProductsController:Controller
    {
         List<Product> urunler = new List<Product>{
            new Product{
                productId = 1,
                productName = "Samsung S24 Ultra",
                productDetail = "Samsung S24 Ultra 512 GB SSD 16 GB RAM",
                productPrice = 70000,
                productImage = "tel-1.jpg",
                productIsStock = true,
                IsHome = true
                
            },
            new Product{
                productId = 2,
                productName = "Iphone 14 Pro",
                productDetail = "Iphone 14 Pro 512 GB SSD 16 GB RAM",
                productPrice = 120000,
                productImage = "tel-2.jpg",
                productIsStock = true,
                IsHome = true
            },
            new Product{
                productId = 3,
                productName = "Google Pixel 7",
                productDetail = "Google Pixel 7 128 GB SSD 8 GB RAM",
                productPrice = 60000,
                productImage = "tel-3.jpg",
                productIsStock = true,
                IsHome = false
            },
            new Product{
                productId = 4,
                productName = "Xiaomi 13 Pro",
                productDetail = "Xiaomi 13 Pro 256 GB SSD 12 GB RAM",
                productPrice = 50000,
                productImage = "tel-4.jpg",
                productIsStock = true,
                IsHome = false
            },
            new Product{
                productId = 5,
                productName = "Oppo Find X5 Pro",
                productDetail = "Oppo Find X5 Pro 256 GB SSD 12 GB RAM",
                productPrice = 40000,
                productImage = "tel-5.jpg",
                productIsStock = true,
                IsHome = false
            }
        };
        public ActionResult Index(){

     


            return View(urunler);
        }

        public ActionResult List(){
            
            return View(urunler);
        }

        public ActionResult Details(int id){

        Product? urun = urunler.Where(m => m.productId == id).FirstOrDefault(); 
  
        
        return View(urun);
        }

        public ActionResult Update(){
            return View();
        }

        
        
    }

Views/Course/Details.cshtml
@model Course



<div class="row justify-content-center mt-5">
    <div class="col-md-6 col-lg-4">
        <div class="card text-center">
            <img src="~/img/@Model.Image" alt="@Model.Title" class="card-img-top img-fluid" />
            <div class="card-body">
                <h1 class="card-title">@Model.Title</h1>
                <p class="card-text">@Model.Title</p>
                <p class="card-text">
                    <strong>Açıklama:</strong> Bu kurs hakkında daha fazla bilgi edinin.
                </p>
                <p class="card-text">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, dolor!
                </p>
              
            </div>
        </div>
    </div>
</div>

Views/Course/Index.cshtml
@model List<Course>
<div class="container">
    
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="mb-3">Kurslar</h1>
    <a class="btn btn-outline-danger" asp-controller="Course" asp-action="List">Tüm Kurslar</a>
</div>

<div class="row">
    @foreach(Course course in Model){
        @if(course.IsHome){
            <div class="col-md-4">
                @await Html.PartialAsync("_CourseCard", course) 
            </div>
        }
    }
</div>
</div>

Views/Course/List.cshtml
@* @model Course[] *@
@model List<Course>

<div class="container">
<h1>Tüm Kurslar</h1>

<div class="row">
@foreach(Course course in Model){
    <div class="col-md-3">
    @await Html.PartialAsync("_CourseCard",course)   
    </div> 
}
</div>
</div>

Views/Course/_CourseCard.cshtml
@model Course


<div class="card mb-5 ">
    <img src="~/img/@Model.Image" class="card-img-top" alt="@Model.Title">
    <div class="card-body ">
        <h5 class="card-title">@Model.Title</h5>
        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, vitae!</p>
        <a asp-controller="Course" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-secondary btn-lg ">İncele</a>
        @* bu sekılde de kullanılabılır *@
        @* <a href="/Course/Details/@Model.Id" class="btn btn-secondary btn-lg ">İncele</a> *@
    </div>
</div>

Views/Home/About.cshtml
<h1>Home/About</h1>

Views/Home/Contact.cshtml
<h1>Home/Contact</h1>

Views/Home/Index.cshtml
<h1>Home/Index</h1>
@* HomeContreollerdaki Toplam keyi ile değerler toplamını kısımda göstermiş olduk *@

<p>

@ViewData["Toplam"] 

</p>

Views/Products/Details.cshtml
@model Product

<h1>Ürün Detay</h1>

<div class="row">
    <div class="col-4">
        <img src="~/img/@Model.productImage" alt="" class="img-fluid" />
    </div>
    <div class="col-8">
        <h1>@Model.productName</h1>
        <p>
            @Model.productDetail
        </p>
        <p>
           @Model.productPrice
        </p>
       
        @if(Model.productIsStock){
            @if(Model.StockPieces > 0){

        <p class="text-success text-sm">
         Ürün Satışta
        </p>

            }
            else{
                <p class="text-sm text-danger">Stok Yeterli Değil</p>
            }
        }
        else{
           <p class="text-sm text-danger">Ürün Satışta Değil</p>
        }
    </div>
</div>

Views/Products/Index.cshtml
@model List<Product>


<div class="container">

<div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="mb-3">Ürünler</h1>
    <a class="btn btn-outline-danger" asp-controller="Products" asp-action="List">Tüm Ürünler</a>
</div>

    <div class="row">
        
@foreach(Product urunler in Model){
      @if(urunler.IsHome && urunler.productIsStock){
        <div class="col-md-3">      
       <div class="card mb-5 ">
    <img src="~/img/@urunler.productImage" class="card-img-top" alt="@urunler.productName">
    <div class="card-body ">
        <h5 class="card-title">@urunler.productName</h5>
        <p class="card-text">@urunler.productDetail</p>
        <p class="card-text">@urunler.productPrice.ToString("C")</p> 
        @* Türkçe kültürde: "1.234,56 ₺"
        İngilizce kültürde: "$1,234.56" *@
        <a href="/Products/Details/@urunler.productId" class="btn btn-secondary btn-lg ">İncele</a>
    </div>
</div>


        </div>
      }
   
       
    

}
   </div>

</div>

Views/Products/List.cshtml
@model List<Product>


<div class="container">
    <h1>Products/List</h1>
<div class="row">

    @foreach(Product urun in Model)
    {
        @if(urun.productIsStock)
        {
            <div class="col-4">
            <div class="card mb-3">
                <div class="col-md-4">
                    <img src="~/img/@urun.productImage" class="img-fluid rounded-start" >
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                    <h5 class="card-title">@urun.productName</h5>
                    <p class="card-text">@urun.productDetail</p>

                    @if(!urun.productIsStock)
                    {
                        <p class="text-danger text-sm">Satışta Değil</p>
                    }

                    <a href="/Products/Details/@urun.productId" class="btn btn-primary btn-sm">Detail</a>
                    </div>
                </div>
            </div>
        </div>
        }

    }

</div>
</div>

Views/Products/Update.cshtml
<h1>Products/Update</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>Document</title>
</head>
<body>
    <header>
     @await Html.PartialAsync("_Navbar")
   </header>
   <main>
   @RenderBody()
   </main>
</body>
</html>

Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme= "dark">
        <div class="container">
            <a class="navbar-brand" href="/">App</a>

           <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>

                <li  class="nav-item">
                    <a class="nav-link" asp-controller="Course" asp-action="Index">Course</a>
                </li>
                <li  class="nav-item">
                    <a class="nav-link" asp-controller="Products" asp-action="Index">Products</a>
                </li>
            </ul>
        </div>
   </nav>